use asianinc_subs;

insert into akj9c_ads_cities
(city_name, city_state)
values
('Alameda', 'CA'),
('Albany', 'CA'),
('American Canyon', 'CA'),
('Antioch', 'CA'),
('Atherton', 'CA'),
('Belmont', 'CA'),
('Belvedere', 'CA'),
('Benicia', 'CA'),
('Berkeley', 'CA'),
('Brentwood', 'CA'),
('Brisbane', 'CA'),
('Burlingame', 'CA'),
('Calistoga', 'CA'),
('Campbell', 'CA'),
('Clayton', 'CA'),
('Cloverdale', 'CA'),
('Colma', 'CA'),
('Concord', 'CA'),
('Corte Madera', 'CA'),
('Cotati', 'CA'),
('Cupertino', 'CA'),
('Daly City', 'CA'),
('Danville', 'CA'),
('Dixon', 'CA'),
('Dublin', 'CA'),
('East Palo Alto', 'CA'),
('El Cerrito', 'CA'),
('Emeryville', 'CA'),
('Fairfax', 'CA'),
('Fairfield', 'CA'),
('Foster City', 'CA'),
('Fremont', 'CA'),
('Gilroy', 'CA'),
('Half Moon Bay', 'CA'),
('Hayward', 'CA'),
('Healdsburg', 'CA'),
('Hercules', 'CA'),
('Hillsborough', 'CA'),
('Lafayette', 'CA'),
('Larkspur', 'CA'),
('Livermore', 'CA'),
('Los Altos', 'CA'),
('Los Altos Hills', 'CA'),
('Los Gatos', 'CA'),
('Martinez', 'CA'),
('Menlo Park', 'CA'),
('Mill Valley', 'CA'),
('Millbrae', 'CA'),
('Milpitas', 'CA'),
('Monte Sereno', 'CA'),
('Moraga', 'CA'),
('Morgan Hill', 'CA'),
('Mountain View', 'CA'),
('Napa', 'CA'),
('Newark', 'CA'),
('Novato', 'CA'),
('Oakland', 'CA'),
('Oakley', 'CA'),
('Orinda', 'CA'),
('Pacifica', 'CA'),
('Palo Alto', 'CA'),
('Petaluma', 'CA'),
('Piedmont', 'CA'),
('Pinole', 'CA'),
('Pittsburg', 'CA'),
('Pleasant Hill', 'CA'),
('Pleasanton', 'CA'),
('Portola Valley', 'CA'),
('Redwood City', 'CA'),
('Richmond', 'CA'),
('Rio Vista', 'CA'),
('Rohnert Park', 'CA'),
('Ross', 'CA'),
('San Anselmo', 'CA'),
('San Bruno', 'CA'),
('San Carlos', 'CA'),
('San Francisco', 'CA'),
('San Jose', 'CA'),
('San Leandro', 'CA'),
('San Mateo', 'CA'),
('San Pablo', 'CA'),
('San Rafael', 'CA'),
('San Ramon', 'CA'),
('Santa Clara', 'CA'),
('Santa Rosa', 'CA'),
('Saratoga', 'CA'),
('Sausalito', 'CA'),
('Sebastopol', 'CA'),
('Sonoma', 'CA'),
('South San Francisco', 'CA'),
('St. Helena', 'CA'),
('Suisun City', 'CA'),
('Sunnyvale', 'CA'),
('Tiburon', 'CA'),
('Union City', 'CA'),
('Vacaville', 'CA'),
('Vallejo', 'CA'),
('Walnut Creek', 'CA'),
('Windsor', 'CA'),
('Woodside', 'CA'),
('Yountville', 'CA')
;